apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-deployment-prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:miw1513/k8s-deployment-prd.git
    targetRevision: main
    path: ./
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: application-prd
  syncPolicy:
    automated:
      prune: true