apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:miw1513/k8s-deployment.git
    targetRevision: main
    path: cart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true